---
version: '3.8'

include:
  - path: resources/adguard.yaml
    project_directory: .
  - path: resources/prowlarr.yaml
    project_directory: .
  - path: resources/sonarr.yaml
    project_directory: .
  - path: resources/radarr.yaml
    project_directory: .
  - path: resources/lidarr.yaml
    project_directory: .

networks:
  yarr-net:
    ipam:
      driver: default
      config:
        - subnet: 171.18.18.0/24
