services:
  adguard-home:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped

    volumes:
      - ./server/configs/adguard/work:/opt/adguardhome/work
      - ./server/configs/adguard/conf:/opt/adguardhome/conf

    ports:
      # :: We don't expose the plain DNS ports because nothing outside of this
      #    compose cluster should be using this DNS --- only services in this
      #    cluster will be resolving through it.

      # :: You will need to map ports 80, 443, and 3000 to your host to be able
      #    to manage it using the web interface. Which ports are available to you
      #    will differ based on your hosting requirements.
      - 3010:80/tcp
      # - 443:443/tcp
      # - 443:443/udp
      - 3000:3000/tcp

    networks:
      yarr-net:
        ipv4_address: 171.18.18.10
