services:
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.11.4
    restart: unless-stopped

    environment:
      - TZ=${TIMEZONE}

    volumes:
      - ./server/configs/prowlarr/config:/config

    ports:
      - ${PROWLARR_PORT}:9696

    dns: 171.18.18.10
    networks:
      yarr-net:

    depends_on:
      - adguard-home
