services:
  adguard-home:
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped

    volumes:
      - ./server/configs/adguard/work:/opt/adguardhome/work
      - ./server/configs/adguard/conf:/opt/adguardhome/conf

    ports:
      - 3053:53/tcp
      - 3053:53/udp
      # - 67:67/udp
      # - 68:68/udp
      # - 68:68/tcp
      - 3010:80/tcp
      # - 443:443/tcp
      # - 443:443/udp
      - 3000:3000/tcp
